<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>mall-parent</artifactId>
        <groupId>com.jiang</groupId>
        <version>2.0.1</version>
    </parent>
    <artifactId>mall-admin</artifactId>
    <version>2.0.1</version>
    <name>mall-admin</name>
    <description>mall主模块</description>
    <url/>
    <licenses>
        <license>
            <name>Mulan PSL v2</name>
            <url>http://license.coscl.org.cn/MulanPSL2</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>ab1213home</id>
            <name>jiangrongjun</name>
            <email>jiangrongjun2004@163.com</email>
            <organization>jiangrongjun</organization>
            <organizationUrl>https://github.com/ab1213home</organizationUrl>
            <roles>
                <role>developer</role>
            </roles>
            <timezone>+8</timezone>
        </developer>
    </developers>
	<scm>
        <connection>scm:git:https://github.com/ab1213home/mall/master.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:ab1213home/develop.git</developerConnection>
        <tag>2.0.1</tag>
        <url>https://github.com/ab1213home/mall</url>
    </scm>
    <properties>
        <java.version>17</java.version>
        <mall.version>2.0.1</mall.version>
    </properties>
    <dependencies>

        <!-- 数据库迁移 -->
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
        </dependency>

        <dependency>
			<groupId>com.jiang</groupId>
			<artifactId>mall-email</artifactId>
		</dependency>
		<dependency>
			<groupId>com.jiang</groupId>
			<artifactId>mall-user</artifactId>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>com.jiang</groupId>-->
<!--			<artifactId>mall-system</artifactId>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>com.jiang</groupId>-->
<!--			<artifactId>mall-task</artifactId>-->
<!--		</dependency>-->
		<dependency>
			<groupId>com.jiang</groupId>
			<artifactId>mall-file</artifactId>
		</dependency>
        <dependency>
            <groupId>com.jiang</groupId>
			<artifactId>mall-captcha</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jiang</groupId>
            <artifactId>mall-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jiang</groupId>
            <artifactId>mall-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jiang</groupId>
            <artifactId>mall-banner</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jiang</groupId>
			<artifactId>mall-seo</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jiang</groupId>
			<artifactId>mall-monitor</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jiang</groupId>
			<artifactId>mall-pay</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jiang</groupId>
			<artifactId>mall-product</artifactId>
        </dependency>

        <!--        <dependency>-->
<!--            <groupId>com.jiang</groupId>-->
<!--			<artifactId>mall-websocket</artifactId>-->
<!--        </dependency>-->
    </dependencies>

    <build>
        <finalName>mall-${mall.version}</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**</include>
                </includes>
                <excludes>
                    <exclude>static/text/**</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>..</directory>
                <includes>
                    <include>README.md</include>
                </includes>
            </resource>
            <resource>
                <directory>..</directory>
                <includes>
                    <include>LICENSE</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.5.15</version>
                <configuration>
                    <fork>true</fork> <!-- 如果没有该配置，devtools不会生效 -->
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    <warName>${project.artifactId}</warName>
                </configuration>
           </plugin>
            <plugin>
                <groupId>io.github.git-commit-id</groupId>
                <artifactId>git-commit-id-maven-plugin</artifactId>
                <version>9.0.1</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.json</generateGitPropertiesFilename>
                    <includeOnlyProperties>
                        <includeOnlyProperty>^git.build.(time|version)$</includeOnlyProperty>
                        <includeOnlyProperty>^git.commit.id.(abbrev|full)$</includeOnlyProperty>
                    </includeOnlyProperties>
                    <format>json</format>
                    <commitIdGenerationMode>full</commitIdGenerationMode>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
